[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "mau_html_visitor"
version = "3.0.0"
description = "A visitor for Mau that converts the AST into HTML"
authors = [{name = "Leonardo Giordani", email = "giordani.leonardo@gmail.com"}]
license = {file = "LICENSE"}
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "License :: OSI Approved :: MIT License",
  "Intended Audience :: Developers",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Topic :: Software Development :: Libraries :: Python Modules",
]
requires-python = ">=3.10"
dependencies = [
  "mau>=5.0.0,<6.0.0",
  # The HTML visitor code contains a custom
  # formatter that is based on the internal
  # mechanisms of Pygments highlighting.
  # This means that unfortunately we need
  # to be careful with any Pygments update.
  "Pygments>=2.18.0,<2.20.0",
  "beautifulsoup4==4.*"
]
readme = "README.md"

[project.urls]
Home = "https://github.com/Project-Mau/mau-html-visitor"

[project.optional-dependencies]
testing = [
  "pytest"
]
development = []

[project.entry-points."mau.visitors"]
visitor = "mau_html_visitor:HtmlVisitor"

